image: node:16.6.0

pipelines:
  pull-requests:
    '**':
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/**
      - step:
          name: 'Check linter errors'
          script:
            - npm run lint:lib
      - step:
          size: 2x
          name: 'Run unit tests'
          script:
            - >
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
                sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
                apt-get update && \
                apt-get install -y google-chrome-stable xvfb procps && \
                apt-get install libxss1
            - apt-get install -y libxtst6 libnss3 libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0      
            - PUPPETEER_CACHE_DIR=/opt/puppeteer npm ci
            - PUPPETEER_CACHE_DIR=/opt/puppeteer npm run pipeline:lib
      - step:
          size: 2x
          name: 'Build'
          script:
            - export NODE_OPTIONS=--max_old_space_size=4096
            - npm run build:lib
  branches:
    master:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/**
      - step:
          name: 'Check linter errors'
          script:
            - npm run lint:lib
      - step:
          size: 2x
          name: 'Run unit tests'
          script:
            - >
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
                sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
                apt-get update && \
                apt-get install -y google-chrome-stable xvfb procps && \
                apt-get install libxss1
            - apt-get install -y libxtst6 libnss3 libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0      
            - PUPPETEER_CACHE_DIR=/opt/puppeteer npm ci
            - PUPPETEER_CACHE_DIR=/opt/puppeteer npm run pipeline:lib
      - step:
          size: 2x
          name: 'Build'
          script:
            - export NODE_OPTIONS=--max_old_space_size=5048
            - npm run build:lib
    develop:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/**
      - step:
          name: 'Check linter errors'
          script:
            - npm run lint:lib
      - step:
          size: 2x
          name: 'Run unit tests'
          script:
            - >
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
                sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
                apt-get update && \
                apt-get install -y google-chrome-stable xvfb procps && \
                apt-get install libxss1
            - apt-get install -y libxtst6 libnss3 libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0      
            - PUPPETEER_CACHE_DIR=/opt/puppeteer npm ci
            - PUPPETEER_CACHE_DIR=/opt/puppeteer npm run pipeline:lib
      - step:
          size: 2x
          name: 'Build'
          script:
            - export NODE_OPTIONS=--max_old_space_size=5048
            - npm run build-prod:lib
